export const storeProducts = [
    {
        id:1,
        title:'tru-box',
        img:"img/thumb-01.jpg",
        price:15000,
        company:"Tru venture",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:1,
        total:4
    },
    {
        id:2,
        title:'badest',
        img:"img/thumb-02.jpg",
        price:2338,
        company:"Tru venture",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:10,
        total:49
    },
    {
        id:3,
        title:'volvo',
        img:"img/thumb-03.jpg",
        price:53330,
        company:"Tru venture",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:13,
        total:16
    },
    {
        id:4,
        title:'touch',
        img:"img/thumb-04.jpg",
        price:4000,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:0
    },
    {
        id:5,
        title:'execusive',
        img:"img/thumb-05.jpg",
        price:11230,
        company:"Tru venture",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:0
    },
    {
        id:6,
        title:'nono-six',
        img:"img/thumb-06.jpg",
        price:11100,
        company:"Tru venture",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:0
    },
    {
        id:7,
        title:'pack',
        img:"img/thumb-07.jpg",
        price:20201,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:10
    },
    {
        id:8,
        title:'clond-one',
        img:"img/thumb-08.jpg",
        price:23110,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:20
    },
    {
        id:9,
        title:'tru xxl',
        img:"img/thumb-09.jpg",
        price:9000,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:5,
        total:19
    },
    {
        id:10,
        title:'block two',
        img:"img/thumb-10.jpg",
        price:6000,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:7
    },
    {
        id:11,
        title:'inno4.3',
        img:"img/thumb-11.jpg",
        price:11020,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:23
    },
    {
        id:12,
        title:'biden 001',
        img:"img/thumb-12.jpg",
        price:21903,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:9
    },
    {
        id:12,
        title:'kitblock',
        img:"img/img-03.jpg",
        price:10000,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:60
    },
    {
        id:13,
        title:'trump 2020',
        img:"img/img-04.jpg",
        price:12010,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:9
    },
    {
        id:14,
        title:'infinite',
        img:"img/img-05.jpg",
        price:21210,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:4
    },

];
export const detailProduct = [
    {
        id:1,
        title:'tru-box',
        img:"img/thumb-01.jpg",
        price:15000,
        company:"Tru venture",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:1,
        total:4
    },
    {
        id:2,
        title:'badest',
        img:"img/thumb-02.jpg",
        price:2338,
        company:"Tru venture",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:10,
        total:49
    },
    {
        id:3,
        title:'volvo',
        img:"img/thumb-03.jpg",
        price:53330,
        company:"Tru venture",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:13,
        total:16
    },
    {
        id:4,
        title:'touch',
        img:"img/thumb-04.jpg",
        price:4000,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:0
    },
    {
        id:5,
        title:'execusive',
        img:"img/thumb-05.jpg",
        price:11230,
        company:"Tru venture",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:0
    },
    {
        id:6,
        title:'nono-six',
        img:"img/thumb-06.jpg",
        price:11100,
        company:"Tru venture",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:0
    },
    {
        id:7,
        title:'pack',
        img:"img/thumb-07.jpg",
        price:20201,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:10
    },
    {
        id:8,
        title:'clond-one',
        img:"img/thumb-08.jpg",
        price:23110,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:20
    },
    {
        id:9,
        title:'tru xxl',
        img:"img/thumb-09.jpg",
        price:9000,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:5,
        total:19
    },
    {
        id:10,
        title:'block two',
        img:"img/thumb-10.jpg",
        price:6000,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:7
    },
    {
        id:11,
        title:'inno4.3',
        img:"img/thumb-11.jpg",
        price:11020,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:23
    },
    {
        id:12,
        title:'biden 001',
        img:"img/thumb-12.jpg",
        price:21903,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:9
    },
    {
        id:12,
        title:'kitblock',
        img:"img/img-03.jpg",
        price:10000,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:60
    },
    {
        id:13,
        title:'trump 2020',
        img:"img/img-04.jpg",
        price:12010,
        company:"google",
        info:"this product is still on a testing mood soon you can  get the full benefit of what tru offers ",
        inCart:false,
        count:0,
        total:9
    },
    {
        id:14,
        title:'infinite',
        img:"img/img-05.jpg",
        price:21210,
        company:"google",
        info:"this product is still on a testing mood soon you we get the full benefit ",
        inCart:false,
        count:0,
        total:4
    },

]